"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 18:49:23.438846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_ecole_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('agreement_number', sa.String(length=80), nullable=False),
    sa.Column('director_name', sa.String(length=120), nullable=False),
    sa.Column('wilaya', sa.String(length=80), nullable=False),
    sa.Column('commune', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('code', 'creneau', 'circulation', name='phaseenum', native_enum=False, length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase', 'date', name='uq_exam_session_phase_date')
    )
    op.create_index(op.f('ix_exam_sessions_date'), 'exam_sessions', ['date'], unique=False)
    op.create_index(op.f('ix_exam_sessions_id'), 'exam_sessions', ['id'], unique=False)
    op.create_table('pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permit_fee', sa.Integer(), nullable=False),
    sa.Column('extra_hour_fee', sa.Integer(), nullable=False),
    sa.Column('exam_fee', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'instructor', 'student', name='roleenum', native_enum=False, length=20), nullable=False),
    sa.Column('gender', sa.Enum('m', 'f', name='genderenum', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('disponible', 'maintenance', name='vehiclestatusenum', native_enum=False, length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('driving_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('phase', sa.Enum('code', 'creneau', 'circulation', name='phaseenum', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'canceled', name='sessionstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('group_label', sa.String(length=80), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driving_sessions_date'), 'driving_sessions', ['date'], unique=False)
    op.create_index('ix_driving_sessions_date_instructor', 'driving_sessions', ['date', 'instructor_id'], unique=False)
    op.create_index(op.f('ix_driving_sessions_id'), 'driving_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_driving_sessions_instructor_id'), 'driving_sessions', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_driving_sessions_vehicle_id'), 'driving_sessions', ['vehicle_id'], unique=False)
    op.create_table('exam_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'refused', 'passed', 'failed', name='registrationstatusenum', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'exam_session_id', name='uq_registration_student_session')
    )
    op.create_index(op.f('ix_exam_registrations_exam_session_id'), 'exam_registrations', ['exam_session_id'], unique=False)
    op.create_index(op.f('ix_exam_registrations_id'), 'exam_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_exam_registrations_student_id'), 'exam_registrations', ['student_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('receipt_number', sa.String(length=30), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('current_phase', sa.Enum('code', 'creneau', 'circulation', name='phaseenum', native_enum=False, length=20), nullable=False),
    sa.Column('hours_code', sa.Float(), nullable=False),
    sa.Column('hours_creneau', sa.Float(), nullable=False),
    sa.Column('hours_circulation', sa.Float(), nullable=False),
    sa.Column('agreed_fee', sa.Integer(), nullable=False),
    sa.Column('course_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    op.create_table('session_attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('credited_hours', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['driving_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_attendance_session_student')
    )
    op.create_index(op.f('ix_session_attendances_id'), 'session_attendances', ['id'], unique=False)
    op.create_index(op.f('ix_session_attendances_session_id'), 'session_attendances', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_attendances_student_id'), 'session_attendances', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_attendances_student_id'), table_name='session_attendances')
    op.drop_index(op.f('ix_session_attendances_session_id'), table_name='session_attendances')
    op.drop_index(op.f('ix_session_attendances_id'), table_name='session_attendances')
    op.drop_table('session_attendances')
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_exam_registrations_student_id'), table_name='exam_registrations')
    op.drop_index(op.f('ix_exam_registrations_id'), table_name='exam_registrations')
    op.drop_index(op.f('ix_exam_registrations_exam_session_id'), table_name='exam_registrations')
    op.drop_table('exam_registrations')
    op.drop_index(op.f('ix_driving_sessions_vehicle_id'), table_name='driving_sessions')
    op.drop_index(op.f('ix_driving_sessions_instructor_id'), table_name='driving_sessions')
    op.drop_index(op.f('ix_driving_sessions_id'), table_name='driving_sessions')
    op.drop_index('ix_driving_sessions_date_instructor', table_name='driving_sessions')
    op.drop_index(op.f('ix_driving_sessions_date'), table_name='driving_sessions')
    op.drop_table('driving_sessions')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('pricing')
    op.drop_index(op.f('ix_exam_sessions_id'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_date'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    op.drop_table('auto_ecole_info')
    # ### end Alembic commands ###
